# see https://pip.pypa.io/en/stable/topics/configuration/

[global]
# Project DB DKS AR
#extra-index-url = https://stefansteinert:<password>@bahnhub.tech.rz.db.de/artifactory/api/pypi/dsd-devops-pypi-prod-local/simple
# Can also work with python "keyring". Note that the invoking interpreter is stored in Keychain.app, causing trouble with venvs. See https://pip.pypa.io/en/stable/topics/authentication/#using-keyring-s-python-module:
#   pipx install keyring
#   keyring set bahnhub.tech.rz.db.de stefansteinert
#   (enter password. Stored in Keychain.app with name=bahnhub.tech.rz.db.de, account=stefansteinert)
#extra-index-url = https://stefansteinert@bahnhub.tech.rz.db.de/artifactory/api/pypi/dsd-devops-pypi-prod-local/simple
# URL schemes that did not work
#extra-index-url = https://bahnhub.tech.rz.db.de/artifactory/api/pypi/dsd-devops-pypi-prod-local/simple
#extra-index-url = https://stefansteinert:@bahnhub.tech.rz.db.de/artifactory/api/pypi/dsd-devops-pypi-prod-local/simple

# Subprocess is the best choice. It will always use the same interpreter from pipx, thereby circumventing the "varying invokers" problem with Keychain.app
#keyring-provider = disabled
keyring-provider = subprocess
#keyring-provider = import
